name: Deploy Laravel Application on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2.3.2

      - name: Setup node package
        uses: actions/setup-node@master

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /

  post-deploy:
    name: Post-Deploy
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run migrations, clear cache for views, config, and routes
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd public_html/
            /opt/cpanel/ea-php80/root/usr/bin/php artisan migrate
            /opt/cpanel/ea-php80/root/usr/bin/php artisan config:clear
            /opt/cpanel/ea-php80/root/usr/bin/php artisan view:clear
            /opt/cpanel/ea-php80/root/usr/bin/php artisan route:cache
            /opt/cpanel/ea-php80/root/usr/bin/php artisan optimize
          host: barta.mehedipata.com
          port: 22
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
